parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''
    env(APP_VERSION): 0.1.0

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello Supremo API Platform
    version: 1.0.0
    # Varnish integration, remove if unwanted
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    collection:
        pagination:
            # Enable/disable pagination
            client_enabled: true
            # Allow user to set how many items per page should be displayed
            client_items_per_page: true
            # default limit
            items_per_page: 20
            # query value of itemsPerPage, set to "limit" to simplify
            items_per_page_parameter_name: limit
    formats:
        jsonapi:  ['application/vnd.api+json'] # Default
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
